import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { NestExpressApplication } from '@nestjs/platform-express';
import helmet from 'helmet';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from './app.module';
import { UPLOAD_ROUTE_PREFIX, resolveUploadDir } from './modules/uploads/uploads.service';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);

  app.use(helmet());

  /*
   * Admin-uploaded images. `crossOriginResourcePolicy` has to be relaxed for this
   * path specifically: Helmet's default `same-origin` value would stop the browser
   * from rendering these in an <img> on the separately-hosted frontend. It stays at
   * the default everywhere else.
   *
   * Safe to serve statically because nothing reaches this directory without first
   * matching an image magic-byte signature, and every filename here was generated by
   * the server — see uploads.service.ts.
   */
  app.useStaticAssets(resolveUploadDir(), {
    prefix: UPLOAD_ROUTE_PREFIX,
    setHeaders: (res) => {
      res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin');
      res.setHeader('X-Content-Type-Options', 'nosniff');
      res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
    },
  });
  // CLIENT_URL restricts CORS to the real deployed frontend in production;
  // unset (local dev) falls back to allowing any origin.
  const clientUrl = process.env.CLIENT_URL;
  app.enableCors(clientUrl ? { origin: clientUrl } : undefined);
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
    }),
  );

  const config = new DocumentBuilder()
    .setTitle('CodeForge API')
    .setDescription('Online Judge REST API')
    .setVersion('0.1')
    .addBearerAuth()
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('docs', app, document);

  const port = process.env.PORT ?? 4000;
  await app.listen(port);
  // eslint-disable-next-line no-console
  console.log(`CodeForge API running on http://localhost:${port} (docs at /docs)`);
}
bootstrap();
